### ISSUE TITLE
x2goclient prompts for password

### ISSUE THREAD

**Issue by mahinlma** [intel/FPGA-Devcloud#12]
@llandis , Please help me to fix this. (Logged in fpga DevCloud node.)
<img width="833" alt="Screenshot 2020-06-17 at 8 27 15 AM" src="https://user-images.githubusercontent.com/7489071/84856937-8f53e380-b085-11ea-86aa-b59dc84cd7fc.png">

**Comment by sneharaogr** [comment]
I ran into the same error. Please help me in resolving this issue.
Thanks!
@xplr1 @llandis

**Comment by llandis** [comment]
Hi Sneha
Which machine are you trying access x2go from?
Would you have some time to get a on a call with us to debug? Would 130 PST on Tuesday 9/22 work?
Thanks
Larry

**Comment by sneharaogr** [comment]
Hi Larry
Sorry for the delayed response. 
> Which machine are you trying access x2go from?

I am using my personal laptop running Ubuntu 20.04. 

> Would you have some time to get a on a call with us to debug? Would 130 PST on Tuesday 9/22 work?

Sure, thanks. That would help.  1:30 am PST on Tuesday would be fine as I am in IST zone. Otherwise, if you meant 1:30 pm PST, then can we reschedule it anytime between 8 am to11 am (PST) or 7 pm to 11 pm (PST)?

Thanks,
Sneha

**Comment by llandis** [comment]
send me an email to lawrence.landis@intel.com I will schedule a MS Teams meeting to look at your setup. Your email address doesnt come through github. Thanks
